### ISSUE TITLE
Mac Ruby Instruction Issues

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/cb-docs#6]
just went through this with Jenn, so have some notes

- How does a user know how to determine if they're using a bash or a zsh environment. If Jenn was doing this on her own, she would have had no idea
- Right now the ruby version listed is 2.7.3
  - should we make that 3.0.1? 
  - we should get that note about versions above the actual install instructions. We installed 2.7.3 then we read the note about versions. Need to make that more prominent. 

Had a long hang while installing rbenv. Might note that as well. 

And if we could figure out a way to clearly describe what Ruby is vs. what a Gem is vs. what bundler is and what jekyll is somewhere, that would be really helpful. Feel like it's getting close but we might want an overview doc that clearly describes all these.  They can be in the glossary but then we need to make sure they're also described/linked in the text itself, at the point of need/learning.

**Comment by evanwill** [comment]
some notes on details:

- zsh is default on "Catalina" +, bash anything before. Do people know their mcos version? Are all macs updated to catalina automatically, or is it like with their phones where older ones get held back. If they have an up to date machine, *and* don't know what we are talking about, they have zsh (?).
- the issue that comes up is zsh the configuration is ~/.zshrc, bash, ~/.bash_profile , need to know for rbenv install
- i think you could test if you have zsh by typing `which zsh`, which should give you a file path if you have it, or nothing if you don't. or I think on mac you can type a random thing like `notarealcommand`, and the error message will be proceeded by the shell you are using? like response = `zsh: notarealcommand: command not found`

**Comment by evanwill** [comment]
I think the "install homebrew" part should be own heading on the page with more context, it was confusing to me that installing ruby, first step is install something else, then install something else, then install ruby!

**Comment by owikle** [comment]
Yeah, I'm working on it now, I was thinking the easiest way is to type something that's not a command. 

Users have to manually update to Catalina, it doesn't happen automatically. And no, the default terminal doesn't get updated to zsh when the computer updates to Catalina, but there is a little message that pops up at the top of the terminal telling people to switch to zsh.

I thought updating to ruby 3.0 causes the problem with webrick? That's why I left it at 2.7.3 for now.

**Comment by evanwill** [comment]
also--question about rbenv install on Mac:

the instructions say to `rbenv init`
which prints out the instructions about what to do to your profile. 
does it correctly print out where to edit the file?

for example, on my computer:

```
rbenv init
# Load rbenv automatically by appending
# the following to ~/.bashrc:

eval "$(rbenv init -)"
```

it says add to `~/.bashrc`, which is correct. Does it seem to detect the correct profile on mac??
Then you could just say check what `rbenv init` says.

**Comment by owikle** [comment]
yeah it does print the correct profile. good point, could get rid of the redundancy.

**Comment by evanwill** [comment]
on ruby version-- Windows Installer is still suggesting 2.7x. 

but now that we have people `bundle install`, I think I will add webrick to the Gemfile to just avoid the issues, so 3 would be fine too. I think most people are still using 2.7x at this point though.

**Comment by evanwill** [comment]
okay-- I did add webrick to the Gemfiles, so 2.7 vs 3. should be non-issue. 
I think you can use language of "latest stable version"?

**Comment by evanwill** [comment]
A couple more rbenv questions:

i guess on Ubuntu I have been suggesting using:

`echo 'eval "$(rbenv init -)"' >> ~/.bashrc`

rather than open file with nano, then paste in and save. --not sure if that is more scary or helpful to save that extra steps?

Then I usually say to check the stable releases according to rbenv, `rbenv install -l`

I wonder if you want to mention how to update? (or maybe this goes in our lib static help docs)
for ruby versions that rbenv knows about--you have to manually update rbenv/ruby-build manually to get the latest ruby versions if you already had rbenv installed--otherwise you only see the stable versions when you first installed rbenv. Also brew actually installs both rbenv and ruby-build, which it doesn't make clear, which can be confusing if you read rbenv docs (which are confusing).

**Comment by owikle** [comment]
I think rbenv install -l is more confusing to beginners because it lists several stable releases. Seems easier to have them just go look at the site, where one is prominent.

I removed the nano instructions and just have them using the command to add it to the file now. I think it obscures things a little bit, but probably less ways to skip a step or mess up.

I don't think the rbenv update info should go on the page, but we could link to it from there. Should it be in libstatic or the glossary?
